//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Audio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatAudio;

public interface AudioServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default String sendVoiceMessage(String senderId, String receiverIdOrGroupId, byte[] audioData)
    {
        return sendVoiceMessage(senderId, receiverIdOrGroupId, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String sendVoiceMessage(String senderId, String receiverIdOrGroupId, byte[] audioData, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceMessageAsync(senderId, receiverIdOrGroupId, audioData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> sendVoiceMessageAsync(String senderId, String receiverIdOrGroupId, byte[] audioData)
    {
        return _iceI_sendVoiceMessageAsync(senderId, receiverIdOrGroupId, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> sendVoiceMessageAsync(String senderId, String receiverIdOrGroupId, byte[] audioData, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceMessageAsync(senderId, receiverIdOrGroupId, audioData, context, false);
    }

    /**
     * @hidden
     * @param iceP_senderId -
     * @param iceP_receiverIdOrGroupId -
     * @param iceP_audioData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_sendVoiceMessageAsync(String iceP_senderId, String iceP_receiverIdOrGroupId, byte[] iceP_audioData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_senderId);
                     ostr.writeString(iceP_receiverIdOrGroupId);
                     ostr.writeByteSeq(iceP_audioData);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default byte[] getVoiceMessage(String messageId)
    {
        return getVoiceMessage(messageId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default byte[] getVoiceMessage(String messageId, java.util.Map<String, String> context)
    {
        return _iceI_getVoiceMessageAsync(messageId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<byte[]> getVoiceMessageAsync(String messageId)
    {
        return _iceI_getVoiceMessageAsync(messageId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<byte[]> getVoiceMessageAsync(String messageId, java.util.Map<String, String> context)
    {
        return _iceI_getVoiceMessageAsync(messageId, context, false);
    }

    /**
     * @hidden
     * @param iceP_messageId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<byte[]> _iceI_getVoiceMessageAsync(String iceP_messageId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<byte[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getVoiceMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_messageId);
                 }, istr -> {
                     byte[] ret;
                     ret = istr.readByteSeq();
                     return ret;
                 });
        return f;
    }

    default CallInfo startCall(String callerId, String targetIdOrGroupId)
    {
        return startCall(callerId, targetIdOrGroupId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CallInfo startCall(String callerId, String targetIdOrGroupId, java.util.Map<String, String> context)
    {
        return _iceI_startCallAsync(callerId, targetIdOrGroupId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<CallInfo> startCallAsync(String callerId, String targetIdOrGroupId)
    {
        return _iceI_startCallAsync(callerId, targetIdOrGroupId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CallInfo> startCallAsync(String callerId, String targetIdOrGroupId, java.util.Map<String, String> context)
    {
        return _iceI_startCallAsync(callerId, targetIdOrGroupId, context, false);
    }

    /**
     * @hidden
     * @param iceP_callerId -
     * @param iceP_targetIdOrGroupId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CallInfo> _iceI_startCallAsync(String iceP_callerId, String iceP_targetIdOrGroupId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CallInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_callerId);
                     ostr.writeString(iceP_targetIdOrGroupId);
                 }, istr -> {
                     CallInfo ret;
                     ret = CallInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default CallInfo joinCall(String userId, String sessionId)
    {
        return joinCall(userId, sessionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CallInfo joinCall(String userId, String sessionId, java.util.Map<String, String> context)
    {
        return _iceI_joinCallAsync(userId, sessionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<CallInfo> joinCallAsync(String userId, String sessionId)
    {
        return _iceI_joinCallAsync(userId, sessionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CallInfo> joinCallAsync(String userId, String sessionId, java.util.Map<String, String> context)
    {
        return _iceI_joinCallAsync(userId, sessionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_sessionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CallInfo> _iceI_joinCallAsync(String iceP_userId, String iceP_sessionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CallInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "joinCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_sessionId);
                 }, istr -> {
                     CallInfo ret;
                     ret = CallInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void endCall(String userId, String sessionId)
    {
        endCall(userId, sessionId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void endCall(String userId, String sessionId, java.util.Map<String, String> context)
    {
        _iceI_endCallAsync(userId, sessionId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> endCallAsync(String userId, String sessionId)
    {
        return _iceI_endCallAsync(userId, sessionId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> endCallAsync(String userId, String sessionId, java.util.Map<String, String> context)
    {
        return _iceI_endCallAsync(userId, sessionId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_sessionId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_endCallAsync(String iceP_userId, String iceP_sessionId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "endCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_sessionId);
                 }, null);
        return f;
    }

    default void registerClient(String userId, AudioClientCallbackPrx callback)
    {
        registerClient(userId, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerClient(String userId, AudioClientCallbackPrx callback, java.util.Map<String, String> context)
    {
        _iceI_registerClientAsync(userId, callback, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerClientAsync(String userId, AudioClientCallbackPrx callback)
    {
        return _iceI_registerClientAsync(userId, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerClientAsync(String userId, AudioClientCallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_registerClientAsync(userId, callback, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_callback -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerClientAsync(String iceP_userId, AudioClientCallbackPrx iceP_callback, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerClient", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeProxy(iceP_callback);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), AudioServicePrx.class, _AudioServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), AudioServicePrx.class, _AudioServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), AudioServicePrx.class, _AudioServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), AudioServicePrx.class, _AudioServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static AudioServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, AudioServicePrx.class, _AudioServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static AudioServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, AudioServicePrx.class, _AudioServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default AudioServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (AudioServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default AudioServicePrx ice_adapterId(String newAdapterId)
    {
        return (AudioServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default AudioServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (AudioServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default AudioServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (AudioServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default AudioServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (AudioServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default AudioServicePrx ice_connectionCached(boolean newCache)
    {
        return (AudioServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default AudioServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (AudioServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AudioServicePrx ice_secure(boolean b)
    {
        return (AudioServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default AudioServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (AudioServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AudioServicePrx ice_preferSecure(boolean b)
    {
        return (AudioServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default AudioServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (AudioServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default AudioServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (AudioServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default AudioServicePrx ice_collocationOptimized(boolean b)
    {
        return (AudioServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default AudioServicePrx ice_twoway()
    {
        return (AudioServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default AudioServicePrx ice_oneway()
    {
        return (AudioServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default AudioServicePrx ice_batchOneway()
    {
        return (AudioServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default AudioServicePrx ice_datagram()
    {
        return (AudioServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default AudioServicePrx ice_batchDatagram()
    {
        return (AudioServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default AudioServicePrx ice_compress(boolean co)
    {
        return (AudioServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default AudioServicePrx ice_timeout(int t)
    {
        return (AudioServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default AudioServicePrx ice_connectionId(String connectionId)
    {
        return (AudioServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default AudioServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (AudioServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::ChatAudio::AudioService";
    }
}
