//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Audio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatAudio;

public interface AudioService extends com.zeroc.Ice.Object
{
    String sendVoiceMessage(String senderId, String receiverIdOrGroupId, byte[] audioData, com.zeroc.Ice.Current current);

    byte[] getVoiceMessage(String messageId, com.zeroc.Ice.Current current);

    CallInfo startCall(String callerId, String targetIdOrGroupId, com.zeroc.Ice.Current current);

    CallInfo joinCall(String userId, String sessionId, com.zeroc.Ice.Current current);

    void endCall(String userId, String sessionId, com.zeroc.Ice.Current current);

    void registerClient(String userId, AudioClientCallbackPrx callback, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::ChatAudio::AudioService",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::ChatAudio::AudioService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendVoiceMessage(AudioService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_senderId;
        String iceP_receiverIdOrGroupId;
        byte[] iceP_audioData;
        iceP_senderId = istr.readString();
        iceP_receiverIdOrGroupId = istr.readString();
        iceP_audioData = istr.readByteSeq();
        inS.endReadParams();
        String ret = obj.sendVoiceMessage(iceP_senderId, iceP_receiverIdOrGroupId, iceP_audioData, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getVoiceMessage(AudioService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_messageId;
        iceP_messageId = istr.readString();
        inS.endReadParams();
        byte[] ret = obj.getVoiceMessage(iceP_messageId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeByteSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_startCall(AudioService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_callerId;
        String iceP_targetIdOrGroupId;
        iceP_callerId = istr.readString();
        iceP_targetIdOrGroupId = istr.readString();
        inS.endReadParams();
        CallInfo ret = obj.startCall(iceP_callerId, iceP_targetIdOrGroupId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        CallInfo.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_joinCall(AudioService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        String iceP_sessionId;
        iceP_userId = istr.readString();
        iceP_sessionId = istr.readString();
        inS.endReadParams();
        CallInfo ret = obj.joinCall(iceP_userId, iceP_sessionId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        CallInfo.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_endCall(AudioService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        String iceP_sessionId;
        iceP_userId = istr.readString();
        iceP_sessionId = istr.readString();
        inS.endReadParams();
        obj.endCall(iceP_userId, iceP_sessionId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_registerClient(AudioService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        AudioClientCallbackPrx iceP_callback;
        iceP_userId = istr.readString();
        iceP_callback = AudioClientCallbackPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.registerClient(iceP_userId, iceP_callback, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "endCall",
        "getVoiceMessage",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "joinCall",
        "registerClient",
        "sendVoiceMessage",
        "startCall"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_endCall(this, in, current);
            }
            case 1:
            {
                return _iceD_getVoiceMessage(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_joinCall(this, in, current);
            }
            case 7:
            {
                return _iceD_registerClient(this, in, current);
            }
            case 8:
            {
                return _iceD_sendVoiceMessage(this, in, current);
            }
            case 9:
            {
                return _iceD_startCall(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
