//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Audio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatAudio;

public class CallInfo implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String sessionId;

    public String webSocketUrl;

    public CallInfo()
    {
        this.sessionId = "";
        this.webSocketUrl = "";
    }

    public CallInfo(String sessionId, String webSocketUrl)
    {
        this.sessionId = sessionId;
        this.webSocketUrl = webSocketUrl;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CallInfo r = null;
        if(rhs instanceof CallInfo)
        {
            r = (CallInfo)rhs;
        }

        if(r != null)
        {
            if(this.sessionId != r.sessionId)
            {
                if(this.sessionId == null || r.sessionId == null || !this.sessionId.equals(r.sessionId))
                {
                    return false;
                }
            }
            if(this.webSocketUrl != r.webSocketUrl)
            {
                if(this.webSocketUrl == null || r.webSocketUrl == null || !this.webSocketUrl.equals(r.webSocketUrl))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::ChatAudio::CallInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sessionId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, webSocketUrl);
        return h_;
    }

    public CallInfo clone()
    {
        CallInfo c = null;
        try
        {
            c = (CallInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.sessionId);
        ostr.writeString(this.webSocketUrl);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.sessionId = istr.readString();
        this.webSocketUrl = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CallInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CallInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        CallInfo v = new CallInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CallInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CallInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CallInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CallInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CallInfo _nullMarshalValue = new CallInfo();

    /** @hidden */
    public static final long serialVersionUID = 6614160616209435650L;
}
