//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public class CallInfo implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String callID;

    public String status;

    public CallInfo()
    {
        this.callID = "";
        this.status = "";
    }

    public CallInfo(String callID, String status)
    {
        this.callID = callID;
        this.status = status;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CallInfo r = null;
        if(rhs instanceof CallInfo)
        {
            r = (CallInfo)rhs;
        }

        if(r != null)
        {
            if(this.callID != r.callID)
            {
                if(this.callID == null || r.callID == null || !this.callID.equals(r.callID))
                {
                    return false;
                }
            }
            if(this.status != r.status)
            {
                if(this.status == null || r.status == null || !this.status.equals(r.status))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Chat::CallInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, callID);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, status);
        return h_;
    }

    public CallInfo clone()
    {
        CallInfo c = null;
        try
        {
            c = (CallInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.callID);
        ostr.writeString(this.status);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.callID = istr.readString();
        this.status = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CallInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CallInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        CallInfo v = new CallInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CallInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CallInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CallInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CallInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CallInfo _nullMarshalValue = new CallInfo();

    /** @hidden */
    public static final long serialVersionUID = 6071375614717621186L;
}
