//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public class UdpConnectionInfo implements java.lang.Cloneable,
                                          java.io.Serializable
{
    public String serverIP;

    public int serverPort;

    public String callID;

    public UdpConnectionInfo()
    {
        this.serverIP = "";
        this.callID = "";
    }

    public UdpConnectionInfo(String serverIP, int serverPort, String callID)
    {
        this.serverIP = serverIP;
        this.serverPort = serverPort;
        this.callID = callID;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        UdpConnectionInfo r = null;
        if(rhs instanceof UdpConnectionInfo)
        {
            r = (UdpConnectionInfo)rhs;
        }

        if(r != null)
        {
            if(this.serverIP != r.serverIP)
            {
                if(this.serverIP == null || r.serverIP == null || !this.serverIP.equals(r.serverIP))
                {
                    return false;
                }
            }
            if(this.serverPort != r.serverPort)
            {
                return false;
            }
            if(this.callID != r.callID)
            {
                if(this.callID == null || r.callID == null || !this.callID.equals(r.callID))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Chat::UdpConnectionInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, serverIP);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, serverPort);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, callID);
        return h_;
    }

    public UdpConnectionInfo clone()
    {
        UdpConnectionInfo c = null;
        try
        {
            c = (UdpConnectionInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.serverIP);
        ostr.writeInt(this.serverPort);
        ostr.writeString(this.callID);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.serverIP = istr.readString();
        this.serverPort = istr.readInt();
        this.callID = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, UdpConnectionInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public UdpConnectionInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        UdpConnectionInfo v = new UdpConnectionInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<UdpConnectionInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, UdpConnectionInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<UdpConnectionInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(UdpConnectionInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final UdpConnectionInfo _nullMarshalValue = new UdpConnectionInfo();

    /** @hidden */
    public static final long serialVersionUID = 74554407243203652L;
}
