//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface VoiceChatPrx extends com.zeroc.Ice.ObjectPrx
{
    default void registerClient(String clientID, ClientCallbackPrx callback)
    {
        registerClient(clientID, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerClient(String clientID, ClientCallbackPrx callback, java.util.Map<String, String> context)
    {
        _iceI_registerClientAsync(clientID, callback, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerClientAsync(String clientID, ClientCallbackPrx callback)
    {
        return _iceI_registerClientAsync(clientID, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerClientAsync(String clientID, ClientCallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_registerClientAsync(clientID, callback, context, false);
    }

    /**
     * @hidden
     * @param iceP_clientID -
     * @param iceP_callback -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerClientAsync(String iceP_clientID, ClientCallbackPrx iceP_callback, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerClient", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_clientID);
                     ostr.writeProxy(iceP_callback);
                 }, null);
        return f;
    }

    default CallInfo requestCall(String fromUser, String toReceiver)
    {
        return requestCall(fromUser, toReceiver, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default CallInfo requestCall(String fromUser, String toReceiver, java.util.Map<String, String> context)
    {
        return _iceI_requestCallAsync(fromUser, toReceiver, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<CallInfo> requestCallAsync(String fromUser, String toReceiver)
    {
        return _iceI_requestCallAsync(fromUser, toReceiver, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<CallInfo> requestCallAsync(String fromUser, String toReceiver, java.util.Map<String, String> context)
    {
        return _iceI_requestCallAsync(fromUser, toReceiver, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toReceiver -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<CallInfo> _iceI_requestCallAsync(String iceP_fromUser, String iceP_toReceiver, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<CallInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "requestCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toReceiver);
                 }, istr -> {
                     CallInfo ret;
                     ret = CallInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void endCall(String callID)
    {
        endCall(callID, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void endCall(String callID, java.util.Map<String, String> context)
    {
        _iceI_endCallAsync(callID, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> endCallAsync(String callID)
    {
        return _iceI_endCallAsync(callID, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> endCallAsync(String callID, java.util.Map<String, String> context)
    {
        return _iceI_endCallAsync(callID, context, false);
    }

    /**
     * @hidden
     * @param iceP_callID -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_endCallAsync(String iceP_callID, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "endCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_callID);
                 }, null);
        return f;
    }

    default void sendVoiceMessage(String fromUser, String toReceiver, byte[] audioData)
    {
        sendVoiceMessage(fromUser, toReceiver, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendVoiceMessage(String fromUser, String toReceiver, byte[] audioData, java.util.Map<String, String> context)
    {
        _iceI_sendVoiceMessageAsync(fromUser, toReceiver, audioData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendVoiceMessageAsync(String fromUser, String toReceiver, byte[] audioData)
    {
        return _iceI_sendVoiceMessageAsync(fromUser, toReceiver, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendVoiceMessageAsync(String fromUser, String toReceiver, byte[] audioData, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceMessageAsync(fromUser, toReceiver, audioData, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toReceiver -
     * @param iceP_audioData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendVoiceMessageAsync(String iceP_fromUser, String iceP_toReceiver, byte[] iceP_audioData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toReceiver);
                     ostr.writeByteSeq(iceP_audioData);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoiceChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoiceChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoiceChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoiceChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static VoiceChatPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static VoiceChatPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default VoiceChatPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (VoiceChatPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default VoiceChatPrx ice_adapterId(String newAdapterId)
    {
        return (VoiceChatPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default VoiceChatPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (VoiceChatPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default VoiceChatPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (VoiceChatPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default VoiceChatPrx ice_invocationTimeout(int newTimeout)
    {
        return (VoiceChatPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default VoiceChatPrx ice_connectionCached(boolean newCache)
    {
        return (VoiceChatPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default VoiceChatPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (VoiceChatPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VoiceChatPrx ice_secure(boolean b)
    {
        return (VoiceChatPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default VoiceChatPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (VoiceChatPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VoiceChatPrx ice_preferSecure(boolean b)
    {
        return (VoiceChatPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default VoiceChatPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (VoiceChatPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default VoiceChatPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (VoiceChatPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default VoiceChatPrx ice_collocationOptimized(boolean b)
    {
        return (VoiceChatPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default VoiceChatPrx ice_twoway()
    {
        return (VoiceChatPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default VoiceChatPrx ice_oneway()
    {
        return (VoiceChatPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default VoiceChatPrx ice_batchOneway()
    {
        return (VoiceChatPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default VoiceChatPrx ice_datagram()
    {
        return (VoiceChatPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default VoiceChatPrx ice_batchDatagram()
    {
        return (VoiceChatPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default VoiceChatPrx ice_compress(boolean co)
    {
        return (VoiceChatPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default VoiceChatPrx ice_timeout(int t)
    {
        return (VoiceChatPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default VoiceChatPrx ice_connectionId(String connectionId)
    {
        return (VoiceChatPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default VoiceChatPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (VoiceChatPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Chat::VoiceChat";
    }
}
