//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Audio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let ChatAudio = _ModuleRegistry.module("ChatAudio");

    Slice.defineSequence(ChatAudio, "AudioBytesHelper", "Ice.ByteHelper", true);

    ChatAudio.CallInfo = class
    {
        constructor(sessionId = "", webSocketUrl = "")
        {
            this.sessionId = sessionId;
            this.webSocketUrl = webSocketUrl;
        }

        _write(ostr)
        {
            ostr.writeString(this.sessionId);
            ostr.writeString(this.webSocketUrl);
        }

        _read(istr)
        {
            this.sessionId = istr.readString();
            this.webSocketUrl = istr.readString();
        }

        static get minWireSize()
        {
            return  2;
        }
    };

    Slice.defineStruct(ChatAudio.CallInfo, true, true);

    const iceC_ChatAudio_AudioClientCallback_ids = [
        "::ChatAudio::AudioClientCallback",
        "::Ice::Object"
    ];

    ChatAudio.AudioClientCallback = class extends Ice.Object
    {
    };

    ChatAudio.AudioClientCallbackPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(ChatAudio.AudioClientCallback, ChatAudio.AudioClientCallbackPrx, iceC_ChatAudio_AudioClientCallback_ids, 0,
    {
        "incomingCall": [, , , , , [[7], [7]], , , , ],
        "callEnded": [, , , , , [[7]], , , , ],
        "voiceMessageReceived": [, , , , , [[7], [7], [7]], , , , ]
    });

    const iceC_ChatAudio_AudioService_ids = [
        "::ChatAudio::AudioService",
        "::Ice::Object"
    ];

    ChatAudio.AudioService = class extends Ice.Object
    {
    };

    ChatAudio.AudioServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(ChatAudio.AudioService, ChatAudio.AudioServicePrx, iceC_ChatAudio_AudioService_ids, 0,
    {
        "sendVoiceMessage": [, , , , [7], [[7], [7], ["ChatAudio.AudioBytesHelper"]], , , , ],
        "getVoiceMessage": [, , , , ["ChatAudio.AudioBytesHelper"], [[7]], , , , ],
        "startCall": [, , , , [ChatAudio.CallInfo], [[7], [7]], , , , ],
        "joinCall": [, , , , [ChatAudio.CallInfo], [[7], [7]], , , , ],
        "endCall": [, , , , , [[7], [7]], , , , ],
        "registerClient": [, , , , , [[7], ["ChatAudio.AudioClientCallbackPrx"]], , , , ]
    });
    exports.ChatAudio = ChatAudio;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
