//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Chat = _ModuleRegistry.module("Chat");

    Slice.defineSequence(Chat, "AudioBufferHelper", "Ice.ByteHelper", true);

    Chat.CallInfo = class
    {
        constructor(callID = "", status = "")
        {
            this.callID = callID;
            this.status = status;
        }

        _write(ostr)
        {
            ostr.writeString(this.callID);
            ostr.writeString(this.status);
        }

        _read(istr)
        {
            this.callID = istr.readString();
            this.status = istr.readString();
        }

        static get minWireSize()
        {
            return  2;
        }
    };

    Slice.defineStruct(Chat.CallInfo, true, true);

    const iceC_Chat_ClientCallback_ids = [
        "::Chat::ClientCallback",
        "::Ice::Object"
    ];

    Chat.ClientCallback = class extends Ice.Object
    {
    };

    Chat.ClientCallbackPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.ClientCallback, Chat.ClientCallbackPrx, iceC_Chat_ClientCallback_ids, 0,
    {
        "incomingCall": [, , , , , [[7], [7]], , , , ],
        "callEnded": [, , , , , [[7]], , , , ],
        "voiceMessageReceived": [, , , , , [[7], [7], [7]], , , , ]
    });

    const iceC_Chat_VoiceChat_ids = [
        "::Chat::VoiceChat",
        "::Ice::Object"
    ];

    Chat.VoiceChat = class extends Ice.Object
    {
    };

    Chat.VoiceChatPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.VoiceChat, Chat.VoiceChatPrx, iceC_Chat_VoiceChat_ids, 0,
    {
        "registerClient": [, , , , , [[7], ["Chat.ClientCallbackPrx"]], , , , ],
        "requestCall": [, , , , [Chat.CallInfo], [[7], [7]], , , , ],
        "endCall": [, , , , , [[7]], , , , ],
        "sendVoiceMessage": [, , , , , [[7], [7], ["Chat.AudioBufferHelper"]], , , , ]
    });
    exports.Chat = Chat;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
